# Crawl Data Twitter > 2000 Tweets
The crawling process was done using Tweet-Harvest. Written by Helmi Satria on  March 30th 2024.

In [12]:
#@title Twitter Auth Token
# auth token ambil dari cookies parameter auth token
twitter_auth_token = 'bb2cdbd166bab095ff6560615d5fc4d9401fc441' # change this auth token

In [13]:
# Import required Python package
!pip install pandas

# Install Node.js (because tweet-harvest built using Node.js)
!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,353 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
curl is already the newest version (7.81.0-1ubuntu1.22).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.
gpg: cannot open '/dev/tty': No such device or address
curl: (23) Failed writing body
deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (2,974 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
nodejs is already the newest version (20.20.1-1nodesource1).
0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.
v20.20.1

In [14]:
!apt-get update
!apt-get install -y \
  libatk1.0-0 \
  libatk-bridge2.0-0 \
  libcups2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  libgbm1 \
  libasound2 \
  libpangocairo-1.0-0 \
  libpango-1.0-0 \
  libcairo2 \
  libgtk-3-0

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,435 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libatk-bridge2.0-0 is already the newest version (2.38.0-3).
libatk1.0-0 is already the newest version (2.36.0-3build1).
libcairo2 is already the newest version (1.16.0-5ubuntu2).
libxcomposite1 is already the newest version (1:0.4.5-1build2).
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxkbcommon0 is already the newest version (1.4.0-1).
libxrandr2 is already the newest version (2:1.5.2-1build1).
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgtk-3-0 is already the newest version (3.24.33-1ubuntu2.2).
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 113 not upgraded.

In [15]:
!npx playwright install chromium

⠙⠹⠸⠼⠴⠦╔═══════════════════════════════════════════════════════════════════════════════╗
║ WARNING: It looks like you are running 'npx playwright install' without first ║
║ installing your project's dependencies.                                       ║
║                                                                               ║
║ To avoid unexpected behavior, please install your dependencies first, and     ║
║ then run Playwright's install command:                                        ║
║                                                                               ║
║     npm install                                                               ║
║     npx playwright install                                                    ║
║                                                                               ║
║ If your project does not yet depend on Playwright, first install the          ║
║ applicable npm package (most commonly @playwright/test), and                  ║
║ then run Playwright's install command to download the browsers:               ║
║                                                                               ║
║     npm install @playwright/test                                              ║
║     npx playwright install                                                    ║
║                                                                               ║
╚═══════════════════════════════════════════════════════════════════════════════╝
⠙

In [16]:
# Crawl Data

filename = 'filedataset.csv'
# search_keyword = 'from:ManUtd_ID lang:id since:2025-10-01 until:2026-02-30'
search_keyword = 'from:MelodyUnited lang:id '
limit = 100

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/filedataset.csv, renaming to ./tweets-data/filedataset.old.csv

-- Scrolling... (1) (2)
Filling in keywords: from:MelodyUnited lang:id

 (3) (4)

Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 40

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 60

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/filedataset.csv
Total tweets saved: 80

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 80 tweets, done scrolling...
⠙

In [21]:
import pandas as pd

# Specify the path to your CSV file
file_path = f"/content/tweets-data/ManUtd_ID.csv"

# Read the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

df.to_csv('ManUtd_ID.csv', index=False)

# Display the DataFrame
df.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2026430629664141761,Tue Feb 24 22:54:46 +0000 2026,171,Old Trafford ramah untuk The Eagles. Jadi hari...,2026430629664141761,https://pbs.twimg.com/media/HB9T6crbEAAKcR0.jpg,NaN,in,NaN,0,15,1,https://x.com/undefined/status/202643062966414...,397302261,NaN
1,2026429678349856974,Tue Feb 24 22:50:59 +0000 2026,8,Semoga setiap tahun ada terus momen seperti ini,2026429678349856974,NaN,NaN,in,NaN,0,0,1,https://x.com/undefined/status/202642967834985...,397302261,NaN
2,2026429020536238144,Tue Feb 24 22:48:22 +0000 2026,151,AIG termasuk singkat ya sama kaya AON ya AIG i...,2026429020536238144,NaN,NaN,in,NaN,1,16,12,https://x.com/undefined/status/202642902053623...,397302261,NaN
3,2026428360554066324,Tue Feb 24 22:45:45 +0000 2026,73,Cocok juga ya si kapten pake ini ternyata hehehe,2026428360554066324,NaN,NaN,in,NaN,0,0,2,https://x.com/undefined/status/202642836055406...,397302261,NaN
4,2026428267826393313,Tue Feb 24 22:45:22 +0000 2026,4,Salah satu jersey memorable Manchester United ...,2026428267826393313,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202642826782639...,397302261,NaN

In [22]:
# Cek jumlah data yang didapatkan

num_tweets = len(df)
print(f"Jumlah tweet dalam dataframe adalah {num_tweets}.")

Jumlah tweet dalam dataframe adalah 60.

**DO TEXT PROCESSING HERE!!**

In [25]:
df_result = df.copy()
df_result.head()

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2026430629664141761,Tue Feb 24 22:54:46 +0000 2026,171,Old Trafford ramah untuk The Eagles. Jadi hari...,2026430629664141761,https://pbs.twimg.com/media/HB9T6crbEAAKcR0.jpg,NaN,in,NaN,0,15,1,https://x.com/undefined/status/202643062966414...,397302261,NaN
1,2026429678349856974,Tue Feb 24 22:50:59 +0000 2026,8,Semoga setiap tahun ada terus momen seperti ini,2026429678349856974,NaN,NaN,in,NaN,0,0,1,https://x.com/undefined/status/202642967834985...,397302261,NaN
2,2026429020536238144,Tue Feb 24 22:48:22 +0000 2026,151,AIG termasuk singkat ya sama kaya AON ya AIG i...,2026429020536238144,NaN,NaN,in,NaN,1,16,12,https://x.com/undefined/status/202642902053623...,397302261,NaN
3,2026428360554066324,Tue Feb 24 22:45:45 +0000 2026,73,Cocok juga ya si kapten pake ini ternyata hehehe,2026428360554066324,NaN,NaN,in,NaN,0,0,2,https://x.com/undefined/status/202642836055406...,397302261,NaN
4,2026428267826393313,Tue Feb 24 22:45:22 +0000 2026,4,Salah satu jersey memorable Manchester United ...,2026428267826393313,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202642826782639...,397302261,NaN

In [27]:
#set agar data bisa dilihat dengan lebar kolom maksimal
pd.set_option('display.max_colwidth', None)

In [28]:
#lihat kolom konten
df['full_text'].head(50)

0                                                                                                          Old Trafford ramah untuk The Eagles. Jadi hari Minggu nanti tuh ya .......... https://t.co/GHiEymVPgq
1                                                                                                                                                               Semoga setiap tahun ada terus momen seperti ini
2                  AIG termasuk singkat ya sama kaya AON ya AIG itu dari 2006 sampe 2010 AON itu dari 2010 sampe 2014 Chevrolet lumayan lama tuh Team Viewer juga singkat banget sampe tau-tau Snapdragon hehehe
3                                                                                                                                                               Cocok juga ya si kapten pake ini ternyata hehehe
4                                                                                                                                  Salah satu jersey memorable Manchester United mungkin ya musim 2007-09 ini ya
5                                                                                                                                                            Itupun kalo pas main di UCL aja gak sih waktu itu?
6                                                                                                                                                                          Hehehe iya sih cuma beda font aja ya.
7                                                                                                                                                                              Karena aura juara mungkin ya hehe
8                                                                                                  Alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya. Sesimpel itu aja.
9                                                                                                                                                                     Dia termasuk yang kalem aja ya keliatannya
10    Enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 2004-06 sama 2007-09. Bener katamu yang bedain cuma fontnya aja Terus jersey away biasanya bakal jadi jersey third di musim depannya.
11                                      Inget ini inget musim 2013/14. Kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang. Penasaran Carrick dulu termasuk salah satunya apa bukan yah.
12                                                                                                                  Gas mas cari yang second aja tapi terawat. Biasanya suka ada tuh di lelang jersey kalo lewat
13                                                                                                                   Ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
14                                                                                                                                                                      Bayangin coba semalem Everton menang 3-1
15                                                                                                                                                                                                Masak aer gak?
16                                                                                                                                                              Lumayan kalo jadi uang yah buat beli pemain lagi
17                                                                                                                                                                   Pasti karena kiper dia pas di Ajax juga sih
18                                                                                                                                           Ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
19                                                                                                                                                                          Sangat leluasa yah buat lawan hehehe
20                                                                                                         Old Trafford ramah untuk The Eagles. Jadi hari Minggu nanti tuh ya .......... https://t.co/GHiEymVPgq
21                                                                                                                                                              Semoga setiap tahun ada terus momen seperti ini
22                 AIG termasuk singkat ya sama kaya AON ya AIG itu dari 2006 sampe 2010 AON itu dari 2010 sampe 2014 Chevrolet lumayan lama tuh Team Viewer juga singkat banget sampe tau-tau Snapdragon hehehe
23                                                                                                                                                              Cocok juga ya si kapten pake ini ternyata hehehe
24                                                                                                                                 Salah satu jersey memorable Manchester United mungkin ya musim 2007-09 ini ya
25                                                                                                                                                           Itupun kalo pas main di UCL aja gak sih waktu itu?
26                                                                                                                                                                         Hehehe iya sih cuma beda font aja ya.
27                                                                                                                                                                             Karena aura juara mungkin ya hehe
28                                                                                                 Alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya. Sesimpel itu aja.
29                                                                                                                                                                    Dia termasuk yang kalem aja ya keliatannya
30    Enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 2004-06 sama 2007-09. Bener katamu yang bedain cuma fontnya aja Terus jersey away biasanya bakal jadi jersey third di musim depannya.
31                                      Inget ini inget musim 2013/14. Kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang. Penasaran Carrick dulu termasuk salah satunya apa bukan yah.
32                                                                                                                  Gas mas cari yang second aja tapi terawat. Biasanya suka ada tuh di lelang jersey kalo lewat
33                                                                                                                   Ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
34                                                                                                                                                                      Bayangin coba semalem Everton menang 3-1
35                                                                                                                                                                                                Masak aer gak?
36                                                                                                                                                              Lumayan kalo jadi uang yah buat beli pemain lagi
37                                                                                                                                                                   Pasti karena kiper dia pas di Ajax juga sih
38                                                                                                                                           Ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
39                                                                                                                                                                          Sangat leluasa yah buat lawan hehehe
40                                                                                                         Old Trafford ramah untuk The Eagles. Jadi hari Minggu nanti tuh ya .......... https://t.co/GHiEymVPgq
41                                                                                                                                                              Semoga setiap tahun ada terus momen seperti ini
42                 AIG termasuk singkat ya sama kaya AON ya AIG itu dari 2006 sampe 2010 AON itu dari 2010 sampe 2014 Chevrolet lumayan lama tuh Team Viewer juga singkat banget sampe tau-tau Snapdragon hehehe
43                                                                                                                                                              Cocok juga ya si kapten pake ini ternyata hehehe
44                                                                                                                                 Salah satu jersey memorable Manchester United mungkin ya musim 2007-09 ini ya
45                                                                                                                                                           Itupun kalo pas main di UCL aja gak sih waktu itu?
46                                                                                                                                                                         Hehehe iya sih cuma beda font aja ya.
47                                                                                                                                                                             Karena aura juara mungkin ya hehe
48                                                                                                 Alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya. Sesimpel itu aja.
49                                                                                                                                                                    Dia termasuk yang kalem aja ya keliatannya
Name: full_text, dtype: object

In [43]:
df.columns

Index(['conversation_id_str', 'created_at', 'favorite_count', 'full_text',
       'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location',
       'quote_count', 'reply_count', 'retweet_count', 'tweet_url',
       'user_id_str', 'username'],
      dtype='object')

In [44]:
df['content_clean'] = (
    df['full_text']
    .astype(str)
    .str.lower()
    .str.replace(r'[^\w\s]', '', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

df[['full_text','content_clean']].head()

,full_text,content_clean
0,Old Trafford ramah untuk The Eagles. Jadi hari Minggu nanti tuh ya .......... https://t.co/GHiEymVPgq,old trafford ramah untuk the eagles jadi hari minggu nanti tuh ya httpstcoghieymvpgq
1,Semoga setiap tahun ada terus momen seperti ini,semoga setiap tahun ada terus momen seperti ini
2,AIG termasuk singkat ya sama kaya AON ya AIG itu dari 2006 sampe 2010 AON itu dari 2010 sampe 2014 Chevrolet lumayan lama tuh Team Viewer juga singkat banget sampe tau-tau Snapdragon hehehe,aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe
3,Cocok juga ya si kapten pake ini ternyata hehehe,cocok juga ya si kapten pake ini ternyata hehehe
4,Salah satu jersey memorable Manchester United mungkin ya musim 2007-09 ini ya,salah satu jersey memorable manchester united mungkin ya musim 200709 ini ya

In [47]:
df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_1303/3486918702.py:1: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'].str.replace('[^\w\s]','',regex=True).head(50)

0                                                                                                                       old trafford ramah untuk the eagles jadi hari minggu nanti tuh ya httpstcoghieymvpgq
1                                                                                                                                                            semoga setiap tahun ada terus momen seperti ini
2               aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe
3                                                                                                                                                           cocok juga ya si kapten pake ini ternyata hehehe
4                                                                                                                               salah satu jersey memorable manchester united mungkin ya musim 200709 ini ya
5                                                                                                                                                          itupun kalo pas main di ucl aja gak sih waktu itu
6                                                                                                                                                                       hehehe iya sih cuma beda font aja ya
7                                                                                                                                                                          karena aura juara mungkin ya hehe
8                                                                                                alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya sesimpel itu aja
9                                                                                                                                                                 dia termasuk yang kalem aja ya keliatannya
10    enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 200406 sama 200709 bener katamu yang bedain cuma fontnya aja terus jersey away biasanya bakal jadi jersey third di musim depannya
11                                      inget ini inget musim 201314 kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang penasaran carrick dulu termasuk salah satunya apa bukan yah
12                                                                                                               gas mas cari yang second aja tapi terawat biasanya suka ada tuh di lelang jersey kalo lewat
13                                                                                                               ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
14                                                                                                                                                                   bayangin coba semalem everton menang 31
15                                                                                                                                                                                             masak aer gak
16                                                                                                                                                          lumayan kalo jadi uang yah buat beli pemain lagi
17                                                                                                                                                               pasti karena kiper dia pas di ajax juga sih
18                                                                                                                                       ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
19                                                                                                                                                                      sangat leluasa yah buat lawan hehehe
20                                                                                                                      old trafford ramah untuk the eagles jadi hari minggu nanti tuh ya httpstcoghieymvpgq
21                                                                                                                                                           semoga setiap tahun ada terus momen seperti ini
22              aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe
23                                                                                                                                                          cocok juga ya si kapten pake ini ternyata hehehe
24                                                                                                                              salah satu jersey memorable manchester united mungkin ya musim 200709 ini ya
25                                                                                                                                                         itupun kalo pas main di ucl aja gak sih waktu itu
26                                                                                                                                                                      hehehe iya sih cuma beda font aja ya
27                                                                                                                                                                         karena aura juara mungkin ya hehe
28                                                                                               alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya sesimpel itu aja
29                                                                                                                                                                dia termasuk yang kalem aja ya keliatannya
30    enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 200406 sama 200709 bener katamu yang bedain cuma fontnya aja terus jersey away biasanya bakal jadi jersey third di musim depannya
31                                      inget ini inget musim 201314 kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang penasaran carrick dulu termasuk salah satunya apa bukan yah
32                                                                                                               gas mas cari yang second aja tapi terawat biasanya suka ada tuh di lelang jersey kalo lewat
33                                                                                                               ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
34                                                                                                                                                                   bayangin coba semalem everton menang 31
35                                                                                                                                                                                             masak aer gak
36                                                                                                                                                          lumayan kalo jadi uang yah buat beli pemain lagi
37                                                                                                                                                               pasti karena kiper dia pas di ajax juga sih
38                                                                                                                                       ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
39                                                                                                                                                                      sangat leluasa yah buat lawan hehehe
40                                                                                                                      old trafford ramah untuk the eagles jadi hari minggu nanti tuh ya httpstcoghieymvpgq
41                                                                                                                                                           semoga setiap tahun ada terus momen seperti ini
42              aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe
43                                                                                                                                                          cocok juga ya si kapten pake ini ternyata hehehe
44                                                                                                                              salah satu jersey memorable manchester united mungkin ya musim 200709 ini ya
45                                                                                                                                                         itupun kalo pas main di ucl aja gak sih waktu itu
46                                                                                                                                                                      hehehe iya sih cuma beda font aja ya
47                                                                                                                                                                         karena aura juara mungkin ya hehe
48                                                                                               alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya sesimpel itu aja
49                                                                                                                                                                dia termasuk yang kalem aja ya keliatannya
Name: content_clean, dtype: object

In [48]:
def clean_data(text,column_name):
    df['content_clean'] = df[column_name].str.lower()
    df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)
    return df

<>:3: SyntaxWarning: invalid escape sequence '\w'
<>:3: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_1303/1186799193.py:3: SyntaxWarning: invalid escape sequence '\w'
  df['content_clean'] = df['content_clean'].str.replace('[^\w\s]','',regex=True)

In [49]:
df = clean_data(df, 'full_text')

print(df[['full_text', 'content_clean']])

                                                                                                                                                                                                     full_text  \
0                                                                                                        Old Trafford ramah untuk The Eagles. Jadi hari Minggu nanti tuh ya .......... https://t.co/GHiEymVPgq
1                                                                                                                                                             Semoga setiap tahun ada terus momen seperti ini
2                AIG termasuk singkat ya sama kaya AON ya AIG itu dari 2006 sampe 2010 AON itu dari 2010 sampe 2014 Chevrolet lumayan lama tuh Team Viewer juga singkat banget sampe tau-tau Snapdragon hehehe
3                                                                                                                                                             Cocok juga ya si kapten pake ini ternyata hehehe
4                                                                                                                                Salah satu jersey memorable Manchester United mungkin ya musim 2007-09 ini ya
5                                                                                                                                                          Itupun kalo pas main di UCL aja gak sih waktu itu?
6                                                                                                                                                                        Hehehe iya sih cuma beda font aja ya.
7                                                                                                                                                                            Karena aura juara mungkin ya hehe
8                                                                                                Alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya. Sesimpel itu aja.
9                                                                                                                                                                   Dia termasuk yang kalem aja ya keliatannya
10  Enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 2004-06 sama 2007-09. Bener katamu yang bedain cuma fontnya aja Terus jersey away biasanya bakal jadi jersey third di musim depannya.
11                                    Inget ini inget musim 2013/14. Kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang. Penasaran Carrick dulu termasuk salah satunya apa bukan yah.
12                                                                                                                Gas mas cari yang second aja tapi terawat. Biasanya suka ada tuh di lelang jersey kalo lewat
13                                                                                                                 Ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
14                                                                                                                                                                    Bayangin coba semalem Everton menang 3-1
15                                                                                                                                                                                              Masak aer gak?
16                                                                                                                                                            Lumayan kalo jadi uang yah buat beli pemain lagi
17                                                                                                                                                                 Pasti karena kiper dia pas di Ajax juga sih
18                                                                                                                                         Ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
19                                                                                                                                                                        Sangat leluasa yah buat lawan hehehe
20                                                                                                       Old Trafford ramah untuk The Eagles. Jadi hari Minggu nanti tuh ya .......... https://t.co/GHiEymVPgq
21                                                                                                                                                            Semoga setiap tahun ada terus momen seperti ini
22               AIG termasuk singkat ya sama kaya AON ya AIG itu dari 2006 sampe 2010 AON itu dari 2010 sampe 2014 Chevrolet lumayan lama tuh Team Viewer juga singkat banget sampe tau-tau Snapdragon hehehe
23                                                                                                                                                            Cocok juga ya si kapten pake ini ternyata hehehe
24                                                                                                                               Salah satu jersey memorable Manchester United mungkin ya musim 2007-09 ini ya
25                                                                                                                                                         Itupun kalo pas main di UCL aja gak sih waktu itu?
26                                                                                                                                                                       Hehehe iya sih cuma beda font aja ya.
27                                                                                                                                                                           Karena aura juara mungkin ya hehe
28                                                                                               Alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya. Sesimpel itu aja.
29                                                                                                                                                                  Dia termasuk yang kalem aja ya keliatannya
30  Enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 2004-06 sama 2007-09. Bener katamu yang bedain cuma fontnya aja Terus jersey away biasanya bakal jadi jersey third di musim depannya.
31                                    Inget ini inget musim 2013/14. Kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang. Penasaran Carrick dulu termasuk salah satunya apa bukan yah.
32                                                                                                                Gas mas cari yang second aja tapi terawat. Biasanya suka ada tuh di lelang jersey kalo lewat
33                                                                                                                 Ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
34                                                                                                                                                                    Bayangin coba semalem Everton menang 3-1
35                                                                                                                                                                                              Masak aer gak?
36                                                                                                                                                            Lumayan kalo jadi uang yah buat beli pemain lagi
37                                                                                                                                                                 Pasti karena kiper dia pas di Ajax juga sih
38                                                                                                                                         Ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
39                                                                                                                                                                        Sangat leluasa yah buat lawan hehehe
40                                                                                                       Old Trafford ramah untuk The Eagles. Jadi hari Minggu nanti tuh ya .......... https://t.co/GHiEymVPgq
41                                                                                                                                                            Semoga setiap tahun ada terus momen seperti ini
42               AIG termasuk singkat ya sama kaya AON ya AIG itu dari 2006 sampe 2010 AON itu dari 2010 sampe 2014 Chevrolet lumayan lama tuh Team Viewer juga singkat banget sampe tau-tau Snapdragon hehehe
43                                                                                                                                                            Cocok juga ya si kapten pake ini ternyata hehehe
44                                                                                                                               Salah satu jersey memorable Manchester United mungkin ya musim 2007-09 ini ya
45                                                                                                                                                         Itupun kalo pas main di UCL aja gak sih waktu itu?
46                                                                                                                                                                       Hehehe iya sih cuma beda font aja ya.
47                                                                                                                                                                           Karena aura juara mungkin ya hehe
48                                                                                               Alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya. Sesimpel itu aja.
49                                                                                                                                                                  Dia termasuk yang kalem aja ya keliatannya
50  Enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 2004-06 sama 2007-09. Bener katamu yang bedain cuma fontnya aja Terus jersey away biasanya bakal jadi jersey third di musim depannya.
51                                    Inget ini inget musim 2013/14. Kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang. Penasaran Carrick dulu termasuk salah satunya apa bukan yah.
52                                                                                                                Gas mas cari yang second aja tapi terawat. Biasanya suka ada tuh di lelang jersey kalo lewat
53                                                                                                                 Ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
54                                                                                                                                                                    Bayangin coba semalem Everton menang 3-1
55                                                                                                                                                                                              Masak aer gak?
56                                                                                                                                                            Lumayan kalo jadi uang yah buat beli pemain lagi
57                                                                                                                                                                 Pasti karena kiper dia pas di Ajax juga sih
58                                                                                                                                         Ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
59                                                                                                                                                                        Sangat leluasa yah buat lawan hehehe

                                                                                                                                                                                             content_clean
0                                                                                                                    old trafford ramah untuk the eagles jadi hari minggu nanti tuh ya  httpstcoghieymvpgq
1                                                                                                                                                         semoga setiap tahun ada terus momen seperti ini
2             aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe
3                                                                                                                                                         cocok juga ya si kapten pake ini ternyata hehehe
4                                                                                                                             salah satu jersey memorable manchester united mungkin ya musim 200709 ini ya
5                                                                                                                                                       itupun kalo pas main di ucl aja gak sih waktu itu
6                                                                                                                                                                     hehehe iya sih cuma beda font aja ya
7                                                                                                                                                                        karena aura juara mungkin ya hehe
8                                                                                              alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya sesimpel itu aja
9                                                                                                                                                               dia termasuk yang kalem aja ya keliatannya
10  enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 200406 sama 200709 bener katamu yang bedain cuma fontnya aja terus jersey away biasanya bakal jadi jersey third di musim depannya
11                                    inget ini inget musim 201314 kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang penasaran carrick dulu termasuk salah satunya apa bukan yah
12                                                                                                             gas mas cari yang second aja tapi terawat biasanya suka ada tuh di lelang jersey kalo lewat
13                                                                                                             ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
14                                                                                                                                                                 bayangin coba semalem everton menang 31
15                                                                                                                                                                                           masak aer gak
16                                                                                                                                                        lumayan kalo jadi uang yah buat beli pemain lagi
17                                                                                                                                                             pasti karena kiper dia pas di ajax juga sih
18                                                                                                                                     ku kira saat itu belum nyetel ternyata oh ternyata emang tabiat aja
19                                                                                                                                                                    sangat leluasa yah buat lawan hehehe
20                                                                                                                   old trafford ramah untuk the eagles jadi hari minggu nanti tuh ya  httpstcoghieymvpgq
21                                                                                                                                                        semoga setiap tahun ada terus momen seperti ini
22            aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe
23                                                                                                                                                        cocok juga ya si kapten pake ini ternyata hehehe
24                                                                                                                            salah satu jersey memorable manchester united mungkin ya musim 200709 ini ya
25                                                                                                                                                      itupun kalo pas main di ucl aja gak sih waktu itu
26                                                                                                                                                                    hehehe iya sih cuma beda font aja ya
27                                                                                                                                                                       karena aura juara mungkin ya hehe
28                                                                                             alhamdulillah gak follow dan gak pernah nonton videonya mungkin bukan aku target marketnya sesimpel itu aja
29                                                                                                                                                              dia termasuk yang kalem aja ya keliatannya
30  enaknya jersey tahun tahun segitu ya yang home bisa kepake dua musim 200406 sama 200709 bener katamu yang bedain cuma fontnya aja terus jersey away biasanya bakal jadi jersey third di musim depannya
31                                    inget ini inget musim 201314 kan katanya saat itu ruang ganti kepecah tuh pemain senior pada membangkang penasaran carrick dulu termasuk salah satunya apa bukan yah
32                                                                                                             gas mas cari yang second aja tapi terawat biasanya suka ada tuh di lelang jersey kalo lewat
33                                                                                                             ahh iya sih ya kalo gak salah itu dia baru balik kan ya sekaligus jadi laga terakhir si dia
34                                                                                                                                                                 bayangin coba semalem everton menang 31

In [50]:
#import library spacy
import spacy

In [51]:
#load model spacy untuk text processing
nlp = spacy.load('en_core_web_sm')
phrase = df.loc[2, 'content_clean']
phrase

'aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe'

In [52]:
doc = nlp(phrase)
doc

aig termasuk singkat ya sama kaya aon ya aig itu dari 2006 sampe 2010 aon itu dari 2010 sampe 2014 chevrolet lumayan lama tuh team viewer juga singkat banget sampe tautau snapdragon hehehe

In [53]:
[token for token in doc]

[aig,
 termasuk,
 singkat,
 ya,
 sama,
 kaya,
 aon,
 ya,
 aig,
 itu,
 dari,
 2006,
 sampe,
 2010,
 aon,
 itu,
 dari,
 2010,
 sampe,
 2014,
 chevrolet,
 lumayan,
 lama,
 tuh,
 team,
 viewer,
 juga,
 singkat,
 banget,
 sampe,
 tautau,
 snapdragon,
 hehehe]

In [54]:
list(nlp.Defaults.stop_words)[:10]

['whereby',
 'last',
 '‘ve',
 'where',
 'have',
 'had',
 'many',
 'namely',
 'nevertheless',
 'its']